<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success'] = array(
        'title' => 'Encrypted Cipher',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $direction = array( 0 => 'left', 1 => 'right');

    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter the shift value'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'radios',
        '#options' => $direction,
        '#description' => t('Select shift direction'),
        '#required' => TRUE,
    );
    $form['shift_phrase'] = array(
        '#title' => 'Phrase to encode',
        '#type' => 'textfield',
        '#description' => t('Type phrase to encode'),
        // '#element_validate' => array();
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encode',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $words = explode(" ", strtolower($form_state['values']['shift_phrase']));

    $alphabet = range('a', 'z');
    $flip = array_flip($alphabet);

    $encrypted_words = array();

    foreach ($words as $word) {
            $n = strlen($word);
            $output = "";
                for ($i = 0; $i < $n; $i++) {
                    if ($shift_direction == 1) {
                        $output .= $alphabet[($flip[$word[$i]] + $shift_value) % 26];
                    }
                    if ($shift_direction == 0) {
                        $output .= $alphabet[(26 + $flip[$word[$i]] - $shift_value) % 26];
                    }
                }
            array_push($encrypted_words, $output);
            $encrypted_phrase = implode(" ", $encrypted_words);
    }

    $_SESSION['output'] = "Encrypted Phrase: " . $encrypted_phrase;
    $form_state['redirect'] = 'cipher_success';
}

function cipher_success() {
    return $_SESSION['output'];
}
